language: java
jdk:
- oraclejdk8

branches:
  only:
  - master

env:
  global:
    - MONGO_REPO="http://repo.mongodb.com/apt/ubuntu"
    - REPO_TYPE="precise/mongodb-enterprise/2.6 multiverse"
    - SOURCES_LOC="/etc/apt/sources.list.d/mongodb-enterprise.list"
    - KEY_SERVER="hkp://keyserver.ubuntu.com:80"
    - MONGOD_PARAMS="--setParameter=enableTestCommands=1"
    - MONGOD_OPTS="--dbpath ./data --fork --logpath mongod.log ${MONGOD_PARAMS}"
    - TERM=dumb

before_install:
    # MongoDB Enterprise Edition 2.6
    - sudo apt-key adv --keyserver ${KEY_SERVER} --recv 7F0CEB10
    - echo "deb ${MONGO_REPO} ${REPO_TYPE}" | sudo tee ${SOURCES_LOC}

    # Update all the repositories
    - sudo apt-get update -qq

install:
    # Install MongoDB Enterprise
    - sudo apt-get install mongodb-enterprise-server
    - sudo stop mongod
    - mkdir data
    
    # Install mutt to send via email JARs
    - sudo apt-get install mutt
    - sudo postconf -e mailbox_size_limit=0
    - sudo postconf -e message_size_limit=0
    - sudo /etc/init.d/postfix restart

before_script:
    - mongod ${MONGOD_OPTS}

script:
  - ./gradlew -q assemble
  #- ./gradlew check -i -S -Pquicktest=true
  - ls -la /home/travis/build/matfur92/mongo-java-driver/
  - ls -la /home/travis/build/matfur92/mongo-java-driver/mongo-java-driver/
  - ls -la /home/travis/build/matfur92/mongo-java-driver/mongo-java-driver/build/
  - find /home/travis/build/matfur92/mongo-java-driver/ -name "*.jar"
  - echo "Attached JARs for mongo-java-driver-3.1.0-SNAPSHOT" | mutt -s "mongo-java-driver-3.1.0-SNAPSHOT" mat_fur_92_pub@yahoo.it -a /home/travis/build/matfur92/mongo-java-driver/mongo-java-driver/build/libs/mongo-java-driver-3.1.0-SNAPSHOT.jar
